### ISSUE TITLE
Attempting to view source files causes a crash on v2.2

### ISSUE THREAD

**Issue by alpapado** [vivekratnavel/omniboard#153]
When attempting to view the source files from a run, omniboard crashes with the following error:

```
::ffff:127.0.0.1 - - [02/Oct/2019:09:11:20 +0000] "GET /api/v1/Fs.files?query=%7B%22$or%22:[%7B%22_id%22:%225d8e127fe9f1e755b0257844%22%7D,%7B%22_id%22:%225d8e127fe9f1e755b0257846%22%7D,%7B%22_id%22:%225d8e127fe9f1e755b0257848%22%7
D,%7B%22_id%22:%225d8e039de9f1e7416a850de9%22%7D,%7B%22_id%22:%225d8e127fe9f1e755b0257849%22%7D,%7B%22_id%22:%225d8e127fe9f1e755b025784a%22%7D,%7B%22_id%22:%225d8e127fe9f1e755b025784c%22%7D]%7D HTTP/1.1" 304 - 6.701 ms
(node:16036) DeprecationWarning: GridStore is deprecated, and will be removed in a future version. Please use GridFSBucket instead
An error occurred:  { MongoError: file with id 5d8e127fe9f1e755b0257844 not opened for writing  
    at Function.create (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/error.js:44:12)    
    at /usr/lib/node_modules/omniboard/node_modules/mongodb/lib/gridfs/grid_store.js:948:22                   
    at result (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)        
    at session.endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/sessions.js:135:41) 
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/utils.js:129:55)    
    at cursor.next (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/find_one.js:28:7)     
    at result (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:703:39)
  driver: true,
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^

MongoError: file with id 5d8e127fe9f1e755b0257844 not opened for writing
    at Function.create (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/error.js:44:12)
    at /usr/lib/node_modules/omniboard/node_modules/mongodb/lib/gridfs/grid_store.js:948:22
    at result (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at session.endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/sessions.js:135:41)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.next (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/find_one.js:28:7)
    at result (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/lib/node_modules/omniboard/node_modules/mongodb/lib/core/cursor.js:703:39)
```

**Comment by ksteverson** [comment]
I have the same issue and I think I managed to track down the problem. 

From what I can tell, sacred does not re-upload sources files that did not change. For example, if code.py did not change between runs 1 and 2, then sacred will simply point the run2 source code files  at code.py uploaded for run 1. Everything works fine until you delete run 1 using the omniboard interface this will delete the only entry for code.py and now the source code pointer from run 2 is broken. 

It seems like the fix is having the delete function in omniboard be more cautious about deleting source code file and check to see if any other runs depend on it.
