### ISSUE TITLE
"omniboard -mu ...." seems not to work (BUG)

### ISSUE THREAD

**Issue by TanCari** [vivekratnavel/omniboard#168]
Hi,

using the command

omniboard --mu "mongodb://USERNAME:PASSWORD@HOST:PORT/DB_NAME?authSource=admin"

I get the following error:

[...]\AppData\Roaming\npm\node_modules\omniboard\dist\config\database.js:22
  if (argv['m'] && argv['m'].indexOf(':')) {
                             ^

TypeError: argv.m.indexOf is not a function
    at Object.<anonymous> ([...]\AppData\Roaming\npm\node_modules\omniboard\dist\config\database.js:22:30)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([...]\AppData\Roaming\npm\node_modules\omniboard\dist\app.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([...]\AppData\Roaming\npm\node_modules\omniboard\dist\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    

I have tried with many different combinations, always with the same results. 
On the other side, mongo has access to the same host, port and database 
without problems. That is, the command 

> mongo "mongodb://USERNAME:PASSWORD@HOST:PORT/DB_NAME?authSource=admin" 

works from mongo shell.

Maybe some bug?

Thanx!

**Comment by TyrionWarMage** [comment]
Sure you did use --mu not -mu ? Got the exact same error...

**Comment by vivekratnavel** [comment]
Closing this now. Please reopen if this can be reproduced.
