### ISSUE TITLE
Trouble downloading source - MongoDB error "file not opened for writing"

### ISSUE THREAD

**Issue by lotsoffood** [vivekratnavel/omniboard#177]
Hello,

I'm using Omniboard 2.4.3 with MongoDB 4.0.5. I am trying to download a source file from the Omniboard interface (by clicking the "Download" button) because the source doesn't show up in the interface. Omniboard is throwing the error below, any thoughts?

```
An error occurred:  { MongoError: file with id 5e0fac1261c321594c7886ca not opened for writing
    at Function.create (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:44:12)
    at /usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:948:22
    at result (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at session.endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/sessions.js:135:41)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.next (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/find_one.js:28:7)
    at result (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:703:39)
  driver: true,
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^

MongoError: file with id 5e0fac1261c321594c7886ca not opened for writing
    at Function.create (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:44:12)
    at /usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:948:22
    at result (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at session.endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/sessions.js:135:41)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.next (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/find_one.js:28:7)
    at result (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:703:39)
```

**Comment by vivekratnavel** [comment]
@lotsoffood Thanks for raising this issue. This error is related to this bug #153 

I am going to fix this soon.
